In [457]:
import numpy as np
import pandas as pd

In [458]:
dataset = pd.read_csv('BreastCancerData (4).csv')

In [459]:
dataset

Age        BMI  BreastFeeding  Marital Status  Alcohol  Smoking  \
0      48   8.543723              1               1        0        0   
1      31  10.204207              1               1        0        0   
2      31  13.807133              1               1        0        0   
3      33  14.088867              1               1        1        0   
4      49  14.494061              1               1        0        0   
...   ...        ...            ...             ...      ...      ...   
2383   29  42.647228              1               1        1        0   
2384   29  43.258102              1               1        1        0   
2385   51  44.171130              0               1        1        1   
2386   41  57.760975              1               1        0        0   
2387   35  69.500000              1               1        1        1   

      BreastCancerHistory  Age at firstPeriod  MenstrualCycle  Cancer Positive  
0                       0                  15               1                0  
1                       0                  12               1                0  
2                       0                  14               1                0  
3                       0                  12               1                0  
4                       0                  15               1                0  
...                   ...                 ...             ...              ...  
2383                    0                  12               1                1  
2384                    0                  13               1                1  
2385                    1                  14               0                1  
2386                    0                  13               1                1  
2387                    1                  15               1                1  

[2388 rows x 10 columns]

In [460]:
X = dataset.iloc[:,:9].values

In [461]:
X

array([[48.        ,  8.5437225 ,  1.        , ...,  0.        ,
        15.        ,  1.        ],
       [31.        , 10.20420723,  1.        , ...,  0.        ,
        12.        ,  1.        ],
       [31.        , 13.80713296,  1.        , ...,  0.        ,
        14.        ,  1.        ],
       ...,
       [51.        , 44.17113007,  0.        , ...,  1.        ,
        14.        ,  0.        ],
       [41.        , 57.76097459,  1.        , ...,  0.        ,
        13.        ,  1.        ],
       [35.        , 69.5       ,  1.        , ...,  1.        ,
        15.        ,  1.        ]])

In [462]:
Y = dataset.iloc[:,9].values

In [463]:
Y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [464]:
from sklearn.model_selection import train_test_split

In [465]:
 X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [466]:
from sklearn.preprocessing import StandardScaler

In [467]:
sc = StandardScaler()

In [468]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [469]:
X_train

array([[-0.49883505, -0.31373932,  0.3505266 , ..., -0.17057206,
        -0.65083898,  0.52849164],
       [-1.39840675,  0.04582943,  0.3505266 , ..., -0.17057206,
        -0.06886218,  0.52849164],
       [ 0.01520592,  0.76143525,  0.3505266 , ..., -0.17057206,
        -1.8147926 ,  0.52849164],
       ...,
       [-1.01287602, -0.52087625,  0.3505266 , ..., -0.17057206,
        -0.06886218,  0.52849164],
       [-1.14138627, -0.42179692, -2.8528505 , ..., -0.17057206,
        -0.65083898,  0.52849164],
       [ 0.91477763,  0.43737834,  0.3505266 , ..., -0.17057206,
        -0.65083898,  0.52849164]])

In [470]:
X_test

array([[-1.14138627,  0.72313827,  0.3505266 , ..., -0.17057206,
         1.09509144,  0.52849164],
       [ 0.40073665,  0.09664523,  0.3505266 , ..., -0.17057206,
        -1.23281579,  0.52849164],
       [-0.75585554,  1.42050015,  0.3505266 , ..., -0.17057206,
        -0.06886218,  0.52849164],
       ...,
       [-1.39840675,  0.8141352 ,  0.3505266 , ..., -0.17057206,
         0.51311463,  0.52849164],
       [-1.14138627, -0.23791359,  0.3505266 , ..., -0.17057206,
        -0.65083898,  0.52849164],
       [-1.39840675, -0.66948594,  0.3505266 , ..., -0.17057206,
         0.51311463,  0.52849164]])

In [471]:
from keras.models import Sequential
from keras.layers import Dense

In [472]:
classifier = Sequential()

In [491]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=9))
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

In [492]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier.fit(X_train,Y_train,batch_size=10,epochs=100)

Epoch 1/100
1910/1910 [==============================] - 1s 337us/step - loss: 0.6710 - accuracy: 0.7628
Epoch 2/100
1910/1910 [==============================] - 0s 125us/step - loss: 0.5247 - accuracy: 0.9387
Epoch 3/100
1910/1910 [==============================] - 0s 116us/step - loss: 0.4250 - accuracy: 0.9455
Epoch 4/100
1910/1910 [==============================] - 0s 102us/step - loss: 0.3804 - accuracy: 0.9476
Epoch 5/100
1910/1910 [==============================] - 0s 102us/step - loss: 0.3466 - accuracy: 0.9482
Epoch 6/100
1910/1910 [==============================] - 0s 105us/step - loss: 0.3191 - accuracy: 0.9508
Epoch 7/100
1910/1910 [==============================] - 0s 105us/step - loss: 0.2958 - accuracy: 0.9524
Epoch 8/100
1910/1910 [==============================] - 0s 104us/step - loss: 0.2770 - accuracy: 0.9513
Epoch 9/100
1910/1910 [==============================] - 0s 105us/step - loss: 0.2615 - accuracy: 0.9503
Epoch 10/100
1910/1910 [==============================]

1910/1910 [==============================] - 0s 104us/step - loss: 0.1317 - accuracy: 0.9639
Epoch 79/100
1910/1910 [==============================] - 0s 103us/step - loss: 0.1329 - accuracy: 0.9649
Epoch 80/100
1910/1910 [==============================] - 0s 101us/step - loss: 0.1325 - accuracy: 0.9639
Epoch 81/100
1910/1910 [==============================] - 0s 102us/step - loss: 0.1326 - accuracy: 0.9649
Epoch 82/100
1910/1910 [==============================] - 0s 104us/step - loss: 0.1308 - accuracy: 0.9660
Epoch 83/100
1910/1910 [==============================] - 0s 104us/step - loss: 0.1318 - accuracy: 0.9639
Epoch 84/100
1910/1910 [==============================] - 0s 103us/step - loss: 0.1313 - accuracy: 0.9634
Epoch 85/100
1910/1910 [==============================] - 0s 103us/step - loss: 0.1319 - accuracy: 0.9649
Epoch 86/100
1910/1910 [==============================] - 0s 103us/step - loss: 0.1312 - accuracy: 0.9654
Epoch 87/100
1910/1910 [==============================] - 0

In [493]:
y_pred=classifier.predict(X_test)

In [494]:
y_pred

array([[0.01626008],
       [0.89196604],
       [0.973943  ],
       [0.97354954],
       [0.9772828 ],
       [0.97727907],
       [0.01626008],
       [0.97507733],
       [0.01626008],
       [0.9772832 ],
       [0.92677844],
       [0.01626008],
       [0.01626008],
       [0.97692776],
       [0.9653507 ],
       [0.01626008],
       [0.01626008],
       [0.01626008],
       [0.01626008],
       [0.9468392 ],
       [0.97576797],
       [0.01626008],
       [0.01944499],
       [0.97720087],
       [0.01626008],
       [0.9769099 ],
       [0.977188  ],
       [0.01626008],
       [0.9771968 ],
       [0.01626008],
       [0.97688216],
       [0.9315346 ],
       [0.01626008],
       [0.9740251 ],
       [0.01626008],
       [0.01626008],
       [0.01626008],
       [0.08128979],
       [0.01626008],
       [0.9769577 ],
       [0.977214  ],
       [0.22804594],
       [0.01626008],
       [0.01626008],
       [0.975323  ],
       [0.01626008],
       [0.92432857],
       [0.193

In [495]:
y_pred=(y_pred>0.5)

In [496]:
y_pred

array([[False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [

In [497]:
from sklearn.metrics import confusion_matrix,classification_report

In [498]:
cm = confusion_matrix(Y_test,y_pred)

In [499]:
cm

array([[271,  18],
       [ 13, 176]], dtype=int64)

In [500]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.94      0.95       289
           1       0.91      0.93      0.92       189

    accuracy                           0.94       478
   macro avg       0.93      0.93      0.93       478
weighted avg       0.94      0.94      0.94       478



In [501]:
from sklearn.metrics import accuracy_score

In [502]:
print(accuracy_score(Y_test,y_pred))

0.9351464435146444


In [503]:
import joblib as jb

In [504]:
jb.dump(classifier,'ANN_model_classifier.pkl')

['ANN_model_classifier.pkl']

In [505]:
jb.dump(sc,'ANN_model_sc.pkl')

['ANN_model_sc.pkl']

In [506]:
model1 = jb.load('ANN_model_classifier.pkl')

In [507]:
print(model1.predict(sc.transform([[23,25,1,1,0,0,0,12,1]])))

[[0.01626008]]


In [508]:
print(model1.predict(sc.transform([[23,25,1,1,0,0,0,12,1]]))[0][0]*100)

1.6260083764791489


array([[1.6669692e-05]], dtype=float32)

array([[False]])

array([[False]])

0

['ANN_model.pkl']

array([[False]])

0.1289745792746544

array([[ True]])

99.80126619338989

99.80126619338989

0.0051355753