In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('BreastCancerData (4).csv')

In [3]:
dataset

Age        BMI  BreastFeeding  Marital Status  Alcohol  Smoking  \
0      48   8.543723              1               1        0        0   
1      31  10.204207              1               1        0        0   
2      31  13.807133              1               1        0        0   
3      33  14.088867              1               1        1        0   
4      49  14.494061              1               1        0        0   
...   ...        ...            ...             ...      ...      ...   
2383   29  42.647228              1               1        1        0   
2384   29  43.258102              1               1        1        0   
2385   51  44.171130              0               1        1        1   
2386   41  57.760975              1               1        0        0   
2387   35  69.500000              1               1        1        1   

      BreastCancerHistory  Age at firstPeriod  MenstrualCycle  Cancer Positive  
0                       0                  15               1                0  
1                       0                  12               1                0  
2                       0                  14               1                0  
3                       0                  12               1                0  
4                       0                  15               1                0  
...                   ...                 ...             ...              ...  
2383                    0                  12               1                1  
2384                    0                  13               1                1  
2385                    1                  14               0                1  
2386                    0                  13               1                1  
2387                    1                  15               1                1  

[2388 rows x 10 columns]

In [4]:
X = dataset.iloc[:,:9].values

In [5]:
X

array([[48.        ,  8.5437225 ,  1.        , ...,  0.        ,
        15.        ,  1.        ],
       [31.        , 10.20420723,  1.        , ...,  0.        ,
        12.        ,  1.        ],
       [31.        , 13.80713296,  1.        , ...,  0.        ,
        14.        ,  1.        ],
       ...,
       [51.        , 44.17113007,  0.        , ...,  1.        ,
        14.        ,  0.        ],
       [41.        , 57.76097459,  1.        , ...,  0.        ,
        13.        ,  1.        ],
       [35.        , 69.5       ,  1.        , ...,  1.        ,
        15.        ,  1.        ]])

In [6]:
Y = dataset.iloc[:,9].values

In [7]:
Y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
 X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler

In [26]:
sc = StandardScaler()

array([[-1.14138627,  0.72313827,  0.3505266 , ..., -0.17057206,
         1.09509144,  0.52849164],
       [ 0.40073665,  0.09664523,  0.3505266 , ..., -0.17057206,
        -1.23281579,  0.52849164],
       [-0.75585554,  1.42050015,  0.3505266 , ..., -0.17057206,
        -0.06886218,  0.52849164],
       ...,
       [-1.39840675,  0.8141352 ,  0.3505266 , ..., -0.17057206,
         0.51311463,  0.52849164],
       [-1.14138627, -0.23791359,  0.3505266 , ..., -0.17057206,
        -0.65083898,  0.52849164],
       [-1.39840675, -0.66948594,  0.3505266 , ..., -0.17057206,
         0.51311463,  0.52849164]])

In [24]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
X_train

array([[-0.49883505, -0.31373932,  0.3505266 , ..., -0.17057206,
        -0.65083898,  0.52849164],
       [-1.39840675,  0.04582943,  0.3505266 , ..., -0.17057206,
        -0.06886218,  0.52849164],
       [ 0.01520592,  0.76143525,  0.3505266 , ..., -0.17057206,
        -1.8147926 ,  0.52849164],
       ...,
       [-1.01287602, -0.52087625,  0.3505266 , ..., -0.17057206,
        -0.06886218,  0.52849164],
       [-1.14138627, -0.42179692, -2.8528505 , ..., -0.17057206,
        -0.65083898,  0.52849164],
       [ 0.91477763,  0.43737834,  0.3505266 , ..., -0.17057206,
        -0.65083898,  0.52849164]])

In [14]:
X_test

array([[-1.14138627,  0.72313827,  0.3505266 , ..., -0.17057206,
         1.09509144,  0.52849164],
       [ 0.40073665,  0.09664523,  0.3505266 , ..., -0.17057206,
        -1.23281579,  0.52849164],
       [-0.75585554,  1.42050015,  0.3505266 , ..., -0.17057206,
        -0.06886218,  0.52849164],
       ...,
       [-1.39840675,  0.8141352 ,  0.3505266 , ..., -0.17057206,
         0.51311463,  0.52849164],
       [-1.14138627, -0.23791359,  0.3505266 , ..., -0.17057206,
        -0.65083898,  0.52849164],
       [-1.39840675, -0.66948594,  0.3505266 , ..., -0.17057206,
         0.51311463,  0.52849164]])

In [15]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [16]:
classifier = Sequential()

In [17]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=9))
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

In [18]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
classifier.fit(X_train,Y_train,batch_size=10,epochs=100)

Epoch 1/100
1910/1910 [==============================] - 1s 475us/step - loss: 0.6740 - accuracy: 0.6571
Epoch 2/100
1910/1910 [==============================] - 0s 173us/step - loss: 0.4972 - accuracy: 0.8257
Epoch 3/100
1910/1910 [==============================] - 0s 165us/step - loss: 0.3683 - accuracy: 0.8450
Epoch 4/100
1910/1910 [==============================] - 0s 255us/step - loss: 0.3325 - accuracy: 0.8644
Epoch 5/100
1910/1910 [==============================] - 0s 152us/step - loss: 0.3153 - accuracy: 0.8733
Epoch 6/100
1910/1910 [==============================] - 0s 155us/step - loss: 0.3027 - accuracy: 0.8796
Epoch 7/100
1910/1910 [==============================] - 0s 166us/step - loss: 0.2925 - accuracy: 0.8880
Epoch 8/100
1910/1910 [==============================] - 0s 169us/step - loss: 0.2847 - accuracy: 0.8895
Epoch 9/100
1910/1910 [==============================] - 0s 168us/step - loss: 0.2764 - accuracy: 0.8911
Epoch 10/100
1910/1910 [==============================]

1910/1910 [==============================] - 0s 173us/step - loss: 0.1308 - accuracy: 0.9565
Epoch 79/100
1910/1910 [==============================] - 0s 173us/step - loss: 0.1308 - accuracy: 0.9560
Epoch 80/100
1910/1910 [==============================] - 0s 175us/step - loss: 0.1288 - accuracy: 0.9550
Epoch 81/100
1910/1910 [==============================] - 0s 171us/step - loss: 0.1286 - accuracy: 0.9571
Epoch 82/100
1910/1910 [==============================] - 0s 159us/step - loss: 0.1282 - accuracy: 0.9576
Epoch 83/100
1910/1910 [==============================] - 0s 178us/step - loss: 0.1279 - accuracy: 0.9581
Epoch 84/100
1910/1910 [==============================] - 0s 156us/step - loss: 0.1267 - accuracy: 0.9550
Epoch 85/100
1910/1910 [==============================] - 0s 165us/step - loss: 0.1257 - accuracy: 0.9555
Epoch 86/100
1910/1910 [==============================] - 0s 169us/step - loss: 0.1243 - accuracy: 0.9602
Epoch 87/100
1910/1910 [==============================] - 0

In [19]:
y_pred=classifier.predict(X_test)

In [20]:
y_pred

array([[3.32621485e-03],
       [9.29571569e-01],
       [9.82915878e-01],
       [9.37881768e-01],
       [9.98871624e-01],
       [9.99999285e-01],
       [2.00104532e-05],
       [9.94867444e-01],
       [5.21608740e-02],
       [1.00000000e+00],
       [9.73002732e-01],
       [3.04585509e-03],
       [4.13188864e-05],
       [9.99986053e-01],
       [9.93785858e-01],
       [2.22559024e-07],
       [1.12776430e-02],
       [7.23348698e-04],
       [7.31701948e-06],
       [6.46655202e-01],
       [9.94457245e-01],
       [5.43847345e-02],
       [3.13491553e-01],
       [9.99999881e-01],
       [3.71779133e-05],
       [9.85621631e-01],
       [9.98680890e-01],
       [3.21652405e-02],
       [9.99956250e-01],
       [7.90094782e-06],
       [9.98833477e-01],
       [9.75694656e-01],
       [1.61400421e-05],
       [9.24017727e-01],
       [3.62670544e-05],
       [1.32593603e-04],
       [1.29058380e-02],
       [1.26415208e-01],
       [1.26274303e-04],
       [9.37881768e-01],


In [28]:
y_pred=(y_pred>0.5)

In [29]:
y_pred

array([[False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [